---
version: "3.8"

services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/tax_data.db:/app/tax_data.db
    restart: unless-stopped
    working_dir: /app

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
