---
version: "3.8"

services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
<<<<<<< HEAD
      - ./instance:/app/instance
=======
      - ./tax_data.db:/app/tax_data.db
>>>>>>> f5da1cd871ccba66058bddd3d8b07256bc4152cb
    restart: unless-stopped
    working_dir: /app

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
